### ISSUE TITLE
Show nothing in browser

### ISSUE THREAD

**Issue by trueMiskin** [TheOnlineJudge/ojudge#110]
I want try this out in docker, after I install ojudge, run it and everything looks good. But after access homepage, browser show me nothing.
Log of the first run: [output.log](https://github.com/TheOnlineJudge/ojudge/files/4538706/output.log)

There is my settings:
docker-compose.yml
```yml
version: '3'

services:
  ojudge:
    build: .
    command: build/bin/ojudgeapp --docroot "docroot;/favicon.ico,/css,/resources,/images" --resources-dir /usr/local/share/Wt/resources --http-address 127.0.0.1 --http-port 9090
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: postgres
```
Dockerfile:
```Dockerfile
FROM debian:buster

RUN set -eux; \
    apt-get update; \
    \
    apt-get install -y git cmake g++ postgresql-server-dev-11 \
      graphicsmagick build-essential libboost-all-dev \
      qtbase5-dev pkg-config liboath-dev; \
    \
    git clone https://github.com/emweb/wt.git; \
    cd wt; \
    mkdir build; cd build; \
    cmake ../; make; make install; \
    cd ../..; \
    \
    apt-get update; \
    apt-get install -y libgraphicsmagick++1-dev libgraphicsmagick1-dev; \
    \
    git clone https://github.com/TheOnlineJudge/ojudge.git; \
    cd ojudge; \
    \
    cmake .; \
    make; \
    \
    mkdir -p ~/.config/ojudge/
    
ADD config /root/.config/ojudge/
WORKDIR /ojudge
```

config file
```
[database]
host=db
dbname=postgres
user=postgres
password=
```

Can you help me where is problem?
